### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by wh000wh000** [kukdh1/PAZ-Unpacker#2]
Hi, can I contact by email? We hope to customize the game's multi-language patch.

**Comment by kukdh1** [comment]
What is the meaning of 'customize the game's multi-language patch'?
I saw many language patch for BDO kr/jp server using 'prestringtable' directory. (like this https://www.bdoengpatch.com/)

**Comment by wh000wh000** [comment]
i mean, want to make more of the other games multi-language patch. Involving a number of unpacking and repacket.

**Comment by kukdh1** [comment]
So, do you want me to help or participate in making language patch of any other games?

**Comment by wh000wh000** [comment]
yep . just asking if you Interested

**Comment by kukdh1** [comment]
Sorry, That looks interesting but I have no time to work.

**Comment by wh000wh000** [comment]
That is so.. pity, I really want to work with you. I just want to make sure you know that I do not want to get your labor for free.  If you change your mind, you can find me through wl4@qq.com
