### ISSUE TITLE
Corrupted files

### ISSUE THREAD

**Issue by AMGarkin** [kukdh1/PAZ-Unpacker#3]
In some cases your program produces currupted files.

Even if file.uiOriginalSize < file.uiCompressedSize it still can be compressed. As you have stated in README.md, all compressed files have signature 0x6E, original file size (long), this file size (long). So I have added just simple test if decrypted file starts with 0x6E:

Main.cpp line 376:
` if (bCompressed || decrypted[0] == 0x6E) { `

This change seems to fix the issue. Tested with NA/EU and RU clients.

**Comment by kukdh1** [comment]
Thanks, I fixed it on 1e77f09.
