### ISSUE TITLE
Not an issue, more of a request

### ISSUE THREAD

**Issue by Shadowtrance** [kukdh1/PAZ-Unpacker#4]
Hey,
Firstly, I'd like to say thanks for the great program, has been very useful for a long time. :)

I do have a small request, if possible.
The bdo mobile paz files aren't encrypted, would it be possible to have an option to not check for encryption so it can be used with those paz files as well as pc?

They do unpack fine with quickbms and the blackdesert script (with the no_encryption option set to 1), so nothing else besides encryption has changed.

And sadly i don't really know C++ at all otherwise I'd try to it myself.

Thanks

**Comment by kukdh1** [comment]
Hi, Shadowtrance,

I don't know that there is a way to automatically detect the PAZ files from Mobile or PC,
but you can disable decryption with few code changes.

To disable decryption, change Main.cpp at line 373, 374:
```cpp
  cipher.decrypt(encrypted, length, &decrypted, &length);
  free(encrypted);
```
to
```cpp
  decrypted = encrypted;
```

Thanks.

**Comment by Shadowtrance** [comment]
Thanks for the reply.

I managed to get it to read the paz folder and it sorts into the tree (well there's only one base folder /res/otherfolders).

To do so i have to do the change you mentioned above, and also had to change 
`cipher.decrypt(encrypted, uiPathLength, &decrypted, &uiPathLength);` on line 58 in PazFile.cpp to the same as the Main.cpp change .

And also had to comment out `free(decrypted);` on line 76 in PazFile.cpp for it to work. Sadly though upon extraction of whatever file it appears to be encrypted/unreadable. Without both changes in both files it would just crash when attempting to open the paz folder.

Not really sure where to go from there, my C++ skills are VERY limited to nearly non existent. haha

But thought I'd share anyway, maybe you have some insight.

![ss 2018-04-02 at 04 30 04](https://user-images.githubusercontent.com/1887665/38176224-959860e6-362e-11e8-8b65-88ee3472f912.png)

Edit: this is how they come out with extraction after those changes. (lots of 000's after the end of the image)

![ss 2018-04-02 at 05 36 02](https://user-images.githubusercontent.com/1887665/38240772-dedc4146-3773-11e8-9d2a-419ad1af8a4e.png)
