### ISSUE TITLE
Not an issue, just a question.

### ISSUE THREAD

**Issue by vincenthawke** [kukdh1/PAZ-Unpacker#5]
Hello! I recently got into exploring BDO models and found your unpacking tool extremely helpful and easy to use. However, I didn't expect that I still won't be able to directly use the model data in a 3d render engine to manipulate or view it from different angles. I found a tool that supposedly can do that but the NativeDecompress.dll lib that it uses is Themida protected and not opensource so I prefer not to run it on non-VM. Link: https://www.reddit.com/r/blackdesertonline/comments/434pl2/tool_black_desert_explorer/

Do you have any tips on how to approach viewing the unpacked files in a 3d engine and how to mimic game rendering engine settings? Thank you for your time.

**Comment by kukdh1** [comment]
Hi,

The program you linked is developed with C#, which can be decompiled.
I found following function which converts `*.pac` file into 3D mesh.
You can look more functions with C# decompilers (like [dnspy](https://github.com/0xd4d/dnSpy)) - code is not obfuscated, very easy to read.

```C#
private void parseModel(byte[] modelData, Texture diffuseTex)
{
  using (MemoryStream memoryStream = new MemoryStream(modelData))
  {
    using (BinaryReader binaryReader = new BinaryReader(memoryStream))
    {
      int num = binaryReader.ReadInt32();
      ushort num2 = binaryReader.ReadUInt16();
      binaryReader.BaseStream.Seek(16L, SeekOrigin.Begin);
      bool flag = num2 == 259;
      if (flag)
      {
        byte b = binaryReader.ReadByte();
        binaryReader.ReadBytes((int)(4 * b));
        byte b2 = binaryReader.ReadByte();
        binaryReader.ReadBytes((int)(1 * b2));
        int num3 = binaryReader.ReadInt32();
        int num4 = binaryReader.ReadInt32();
        int num5 = (int)binaryReader.ReadInt16();
        List<Mesh> list = new List<Mesh>();
        for (int i = 0; i < num5; i++)
        {
          bool flag2 = false;
          byte count = binaryReader.ReadByte();
          binaryReader.ReadBytes((int)count);
          ushort num6 = binaryReader.ReadUInt16();
          for (int j = 0; j < 3; j++)
          {
            ushort num7 = binaryReader.ReadUInt16();
            byte[] vertices = binaryReader.ReadBytes((int)(32 * num7));
            uint num8 = binaryReader.ReadUInt32();
            ushort[] array = new ushort[num8];
            int num9 = 0;
            while ((long)num9 < (long)((ulong)num8))
            {
              array[num9] = BitConverter.ToUInt16(binaryReader.ReadBytes(2), 0);
              num9++;
            }
            bool flag3 = flag2;
            if (!flag3)
            {
              flag2 = true;
              Mesh item = new Mesh(vertices, array, diffuseTex);
              list.Add(item);
            }
          }
        }
        this.modelViewer = new Game(800, 600, list);
        this.modelViewer.Run();
      }
    }
  }
}
```

`NativeDecompress.dll` only includes decompress/decrypt function already implemented in my unpacker program, so you don't need to care about it.

Thanks.
